name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2025.1.1"
          install-go: false