name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.x
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - run: go get -u github.com/go-bindata/go-bindata/...
      - run: go-bindata -debug -o ./internal/bindata.go -pkg internal internal/test_databases
      - run: make test
